### ISSUE TITLE
Unable to resolve

### ISSUE THREAD

**Issue by spuder** [Abhishek-070/Dockerhub-Build-Push#3]
I'm attempting to use this repo as shown in the github marketplace

```
name: Docker Build And Push To Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v1
        id: git_checkout

      - name: Build Docker Image
        id: buildAndPushImage
        uses: abhishek-070/docker-image-build-push-action@v1.0
        with:
          registry_url: 'docker.io'
          repository_name: 'spuder/openscad'
          user_name: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image_version: 'v0.0.1'
          docker_file: '.'
      - name: Get pre step result output image_pull_url
        run: echo "The time was ${{ steps.buildAndPushImage.outputs.image_pull_url }}"
```
        
Yet the pipeline always fails with this error. 

```
Current runner version: '2.285.1'
Operating System
Virtual Environment
Virtual Environment Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Unable to resolve action `abhishek-070/docker-image-build-push-action@v1.0`, repository not found
```
